root = "."
tmp_dir = "./bin"

[build]
  cmd = "go build -o ./bin/server ./cmd/api/dev/main.go"
  bin = "./bin/server"
  exclude_dir = ["bin", "vendor", "hack"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "graphql"]
  delay = 1000
  kill_delay = 500
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
