version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: api
    ports:
      - "9000:9000"
    volumes:
      - .:/go/src/app
    env_file:
      - .env
    command: air -c .air.toml
