name: stg-migration

on:
  push:
    branches:
      - main
    paths:
      - migration/**

jobs:
  migration-stg:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1

      - name: build migrate
        env:
          MYSQL_USER: ${{ secrets.STG_MYSQL_USER }}
          MYSQL_HOST: ${{ secrets.STG_MYSQL_HOST }}
          MYSQL_PASSWORD: ${{ secrets.STG_MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.STG_MYSQL_DATABASE }}
        working-directory: migration
        run: |
          docker build . -f docker/planet-scale/Dockerfile -t migration
          docker run --name migration -e MYSQL_USER=${{ env.MYSQL_USER }} -e MYSQL_HOST=${{ env.MYSQL_HOST }} -e MYSQL_PASSWORD=${{ env.MYSQL_PASSWORD }} -e MYSQL_DATABASE=${{ env.MYSQL_DATABASE }} migration
