name: stg-migration

on:
  push:

jobs:
  migration-stg:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1

      - name: build migrate
        env:
          MYSQL_USER: ${{ secrets.STG_MYSQL_USER }}
          MYSQL_HOST: ${{ secrets.STG_MYSQL_HOST }}
          MYSQL_PASSWORD: ${{ secrets.STG_MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.STG_MYSQL_DATABASE }}
        run: |
          docker build . -f migration/docker/planet-scale/Dockerfile -t migration
          docker exec migration mysqldef -u ${{ env.MYSQL_USER }} --host ${{ env.MYSQL_HOST }} -p ${{ env.MYSQL_PASSWORD }} ${{ env.MYSQL_DATABASE }} < migration/schema.sql
